# Site settings
title: Mike Kotsch
email: hi@mikekotsch.de
description: > # this means to ignore newlines until "baseurl:"
  Hi, I’m an Interaction Designer, passionately crazy for knowledge.
baseurl: "" # the subpath of your site, e.g. /blog/
url: “mikekotsch.de” # the base hostname & protocol for your site
twitter_username: mikekotsch
github_username:  mikekotsch

# Build settings
markdown: kramdown
